libuio: fix build issue with gcc-5
Source: MontaVista Software, LLC
MR: 61088
Type: Defect Fix
Disposition: Local
Needs to be upstreamed to meta-openembedded
Description:

1. Add PNBLACKLIST[libuio] = "", to avoid blacklisting libuio recipe, which fails
to build with gcc-5.

2. By default, gcc-5 uses C99 inline semantics, this semantics doesn't
generate externally visible function for inline functions. This results in
below error, when an another translation unit (TU) tries to link with the
inline function,

-- snip --
| x86_64-montavista-linux-libtool: link: x86_64-montavista-linux-gcc -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse --sysroot=/local/jenkins/qemux86-64-4.1-2.0-151014090018/qemux86-64-4.1-2.0-project/tmp/sysroots/qemux86-64 -O2 -pipe -g -feliminate-unused-debug-types -Wl,-O1 -Wl,--hash-style=gnu -o .libs/lsuio lsuio.o  ../src/.libs/libuio.so
| lsuio.o: In function `main':
| /local/jenkins/qemux86-64-4.1-2.0-151014090018/qemux86-64-4.1-2.0-project/tmp/work/core2-64-montavista-linux/libuio/0.2.1-r0.1/git/tools/lsuio.c:85: undefined reference to `uio_mmap'
| collect2: error: ld returned 1 exit status
| make[2]: *** [lsuio] Error 1
-- CUT --

To solve this error and make libuio to compile with both 4.x and 5.x,

1. We can remove 'uio_mmap' inline function definition in uio_mmap.c, and move
   that definition into uio_helper.h file (which is included by lsuio.c) and
   replace inline with "static inline". Similarly it can be done to
   uio_single_munmap and uio_munmap inline functions

2. Add 'extern' keyword in front of uio_mmap inline function declaration , to
   make uio_mmap as a externally visible function, and so that it can be
   linked with other TUs.

Going with option 1.

Reviewed-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>