audit: fix build issue
Source: MontaVista Software, LLC
MR: 61088
Type: Integration
Disposition: Local
Description:

Ugly workaround to fix referring older bits/socket.h header file
in centos 5.6, which doesn't have new macros such as AF_RDS,
AF_LLC, AF_CAN  defined.
bits/socket.h is given by host glibc, since we
don't have an option to upgrade glibc for chroot cent os 5.6; falling
back to link with target's header file, which is incorrect, needed until we
move to cent os 6.x or higher.

Error log:
-- snip --
| gcc  -DHAVE_CONFIG_H -I. -I/local/jenkins/qemux86-64-4.1-2.0-151014090018/qemux86-64-4.1-2.0-project/tmp/work/core2-64-montavista-linux/audit/2.4.3-r8.1/audit-2.4.3/auparse -I..  -I. -I/local/jenkins/qemux86-64-4.1-2.0-151014090018/qemux86-64-4.1-2.0-project/tmp/work/core2-64-montavista-linux/audit/2.4.3-r8.1/audit-2.4.3 -I/local/jenkins/qemux86-64-4.1-2.0-151014090018/qemux86-64-4.1-2.0-project/tmp/work/core2-64-montavista-linux/audit/2.4.3-r8.1/audit-2.4.3/src -I/local/jenkins/qemux86-64-4.1-2.0-151014090018/qemux86-64-4.1-2.0-project/tmp/work/core2-64-montavista-linux/audit/2.4.3-r8.1/audit-2.4.3/lib -isystem/local/jenkins/qemux86-64-4.1-2.0-151014090018/qemux86-64-4.1-2.0-project/tmp/sysroots/x86_64-linux/usr/include -isystem/local/jenkins/qemux86-64-4.1-2.0-151014090018/qemux86-64-4.1-2.0-project/tmp/sysroots/x86_64-linux/usr/include -O2 -pipe '-DTABLE_H="../auparse/flagtab.h"' -O2 -pipe -g -feliminate-unused-debug-types -c -o gen_flagtabs_h-gen_tables.o `test -f '../lib/gen_tables.c' || echo '/local/jenkins/qemux86-64-4.1-2.0-151014090018/qemux86-64-4.1-2.0-project/tmp/work/core2-64-montavista-linux/audit/2.4.3-r8.1/audit-2.4.3/auparse/'`../lib/gen_tables.c
| In file included from /local/jenkins/qemux86-64-4.1-2.0-151014090018/qemux86-64-4.1-2.0-project/tmp/work/core2-64-montavista-linux/audit/2.4.3-r8.1/audit-2.4.3/auparse/../lib/gen_tables.c:81:
| /local/jenkins/qemux86-64-4.1-2.0-151014090018/qemux86-64-4.1-2.0-project/tmp/work/core2-64-montavista-linux/audit/2.4.3-r8.1/audit-2.4.3/auparse/famtab.h:44: error: 'AF_RDS' undeclared here (not in a function)
| /local/jenkins/qemux86-64-4.1-2.0-151014090018/qemux86-64-4.1-2.0-project/tmp/work/core2-64-montavista-linux/audit/2.4.3-r8.1/audit-2.4.3/auparse/famtab.h:49: error: 'AF_LLC' undeclared here (not in a function)
| /local/jenkins/qemux86-64-4.1-2.0-151014090018/qemux86-64-4.1-2.0-project/tmp/work/core2-64-montavista-linux/audit/2.4.3-r8.1/audit-2.4.3/auparse/famtab.h:50: error: 'AF_CAN' undeclared here (not in a function)
-- CUT --

Reviewed-by: Jeremy Puhlman <jpuhlman@mvista.com>
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>