ustr: remove bbappend file, to fix build break during do_patch
Source: MontaVista Software, LLC
MR: 61088
Type: Defect Fix
Disposition: Local
Description:
ustr-gcc-5+.diff is not required, as the upstream ustr recipe
already have a fix to resolve ustr build failure with gcc 5+.
The below commit in meta-selinux layer (master branch)
fixes build failure with gcc 5+, and we just need to pull in
latest changes from meta-selinux layer (master branch).

-- snip --
commit b383d0cbad042c84d40d2c675b0c9608a60f54e2
Author: Robert Yang <liezhi.yang@windriver.com>
Date:   Tue Sep 8 01:21:17 2015 -0700

    ustr: fix build error with gcc 5

    Backport a patch from debian to fix errors as:
    ustr-main.h:1062: multiple definition of `ustrp_setf_owner'

    Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
    Signed-off-by: Joe MacDonald <joe_macdonald@mentor.com>
-- CUT --
Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>