nss: fix build error
Source: MontaVista Software, LLC
MR: 61088
Type: Defect Fix
Disposition: Local
Description:
1. On Ubuntu 14.04, with linker (ld) from binutils-native, nss-native
   fails to build with below error:
-- snip --
| /CGE7_SHDD/qemux86-64-3.18-2.0-150925020231/qemux86-64-3.18-2.0-project/tmp/sysroots/x86_64-linux/usr/bin/binutils-native/ld: this linker was not configured to use sysroots
| collect2: error: ld returned 1 exit status
| make[2]: *** [Linux3.4_x86_64_glibc_PTH_64_OPT.OBJ/nsinstall] Error 1
| make[2]: Leaving directory `/CGE7_SHDD/qemux86-64-3.18-2.0-150925020231/qemux86-64-3.18-2.0-project/tmp/work/x86_64-linux/nss-native/3.19-r1.1/nss-3.19/nss/coreconf/nsinstall'
| make[1]: *** [libs] Error 2
| make[1]: Leaving directory `/CGE7_SHDD/qemux86-64-3.18-2.0-150925020231/qemux86-64-3.18-2.0-project/tmp/work/x86_64-linux/nss-native/3.19-r1.1/nss-3.19/nss/coreconf'
| make: *** [export] Error 2
-- CUT --

   To solve this error, ld was configured to use sysroots by adding below
   line in binutils_2.25.1.bbappend:
   EXTRA_OECONF_class-native += "--with-sysroot=${prefix}"

   With this fix, nss-native builds fine on Ubuntu 14.04. But it
   fails to build on chroot (cent os 5.6) environment with below error:
-- snip --
| /local/jenkins/qemux86-64-4.1-2.0-151008233106/qemux86-64-4.1-2.0-project/tmp/sysroots/x86_64-linux/usr/bin/binutils-native/ld: warning: librt.so.1, needed by /local/jenkins/qemux86-64-4.1-2.0-151008233106/qemux86-64-4.1-2.0-project/tmp/sysroots/x86_64-linux/usr/lib/libnspr4.so, not found (try using -rpath or -rpath-link)
| /local/jenkins/qemux86-64-4.1-2.0-151008233106/qemux86-64-4.1-2.0-project/tmp/sysroots/x86_64-linux/usr/lib/libnspr4.so: undefined reference to `clock_gettime@GLIBC_2.2.5'
| collect2: ld returned 1 exit status
| make[2]: *** [Linux3.4_x86_64_glibc_PTH_64_OPT.OBJ/addbuiltin] Error 1
-- CUT --

   librt.so library is not present in sysroots used by binutils-native, hence add
   explicit entry of '-lrt', so that librt.so library gets pulled in from
   standard host library paths

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>