opensaf: create alias name called openais to resolve runtime dependencies
Source: MontaVista Software, Inc.
MR: 60774
Type: Integration
Disposition: Local
Description:
packagegroup-cgl-middleware has runtime dependency on openais. Since
we chose opensaf over openais, add RPROVIDES to make openais as an
alias name of opensaf and solve runtime dependencies as below;

-- snip --
ERROR: Required build target 'core-image-cgl' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-cgl', 'packagegroup-cgl', 'packagegroup-cgl-middleware', 'openais']
-- CUT --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>